[mgr]
show_hidden = true
sort_by = "extension"
sort_sensitive = true
sort_dir_first = true
show_symlink = true

[preview]
wrap = "yes"

[opener]
edit = [
  { run = "nvim $@", block = true, desc = "Neovim", for="unix" }
]
