theme = "base16_transparent"

[editor]
line-number = "relative"
auto-completion = true
auto-format = true
true-color = true
completion-timeout = 5
completion-trigger-len = 1
completion-replace = true
bufferline = "always"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "<>"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true
follow-symlinks = true

[editor.auto-pairs]
"(" = ")"
"{" = "}"
"[" = "]"
"\"" = "\""
"`" = "`"
"<" = ">"

[editor.auto-save]
focus-lost = true

[keys.normal]
C-s = ":w"
C-q = ":q"
"C-S-q" = ":qa"
C-r = ":run-shell-command cargo run"

[keys.insert]
"C-space" = "completion"
