[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = 'prettier', args = ["--parser", "babel"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "emmet-lsp" ]

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "emmet-lsp" ]

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]
[[language]]
name = "tsx"
# This combines TS, Emmet, and Tailwind into one file type
language-servers = [ "typescript-language-server", "emmet-lsp", "tailwindcss-ls" ]

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]
